apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ga-secrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - name: tcp
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 50Mi
        accessModes:
          - ReadWriteOnce


---
apiVersion: v1
kind: Secret
metadata:
  name: ga-secrets
data:
  MYSQL_ROOT_PASSWORD: cm9vdAo=
