apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  # after the claim is release, the PersistentVolume
  # should be retained (not erased or deleted).
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/tmp/data'
